title = "COS20"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "What we do"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/fhjoanneum"
  twitter = "https://twitter.com/fh_joanneum"
  instagram = "https://www.instagram.com/fh_joanneum/?hl=de"
  youtube = "https://www.youtube.com/user/fhjoanneum"
  github = ""
  gitlab = ""
  linkedin = "https://www.linkedin.com/school/fh-joanneum/?originalSubdomain=at"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-grey"
  featured_image = "/images/pexels-fauxels-3183150.jpg"
  recent_posts_number = 2
  custom_css = ["css/boxes.css"]
  ananke_process_css = true